{{- if .Values.ingress.enabled }}

apiVersion: {{ .Values.ingress.apiversion }}
kind: Ingress
metadata:
  name: ph-ee-zeebe-ops
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
{{- if .Values.ingress.tls }}
  tls:
    hosts:
      "{{ .Values.wildcardhostname }}"
    secretName: "{{ .Values.tls }}"
{{- end }}    
  rules:
  {{- range $key, $value := .Values.global.ingress }}
  {{- range $value.hosts }}
    host: "{{ .Values.hostname }}"
    http:
      paths:
        path: "{{ .Values.ingress.path }}"
        pathType: Prefix
{{- if .Values.ingress.backend }}          
        backend:
{{ toYaml .Values.ingress.backend | indent 12 }}
{{- end }}
  {{- end }}
  {{- end }}
  
{{- end }}
