{{- if .Values.ingress.enabled -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ph-ee-connector-bulk
  labels:
    app: ph-ee-connector-bulk
    release: {{ .Release.Name | quote }}
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}

{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
{{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - "{{ .Values.wildcardhostname }}"
    secretName: "{{ .Values.tls }}"
{{- end }}    
  rules:
  - host: "{{ .Values.hostname }}"
    http:
      paths:
      - path: "{{ .Values.ingress.path }}"
        pathType: Prefix     
        backend:
{{- if .Values.ingress.backend }}
{{ toYaml .Values.ingress.backend | indent 14 }}
{{- end }} 

{{- end }}