service:
  apiversion: "v1"

secret:
  apiversion: "v1"

configmap:
  apiversion: "v1"

enabled: true
image: ""
imageTag: latest
imagePullPolicy: "Always"
SPRING_PROFILES_ACTIVE: ""
hostname: "amsmifos.sandbox.mifos.io"
ams_local_enabled: true
ams_local_interop_host : "https://fynams.sandbox.mifos.io"
ams_local_customer_host : "https://fynams.sandbox.mifos.io"
ams_local_account_host : "https://fynams.sandbox.mifos.io"
ams_local_auth_host : "https://fynams.sandbox.mifos.io"
ams_local_loan_host : "https://fynams.sandbox.mifos.io/"
dfspids: "gorilla,rhino"
extraInitContainers: ""
## tenants properties have been moved to fin12
limits:
  cpu: "500m"
  memory: "512M"
requests:
  cpu: "100m"
  memory: "256M"
wildcardhostname: ""  
ingress:
  enabled: false
  className: "nginx"
  pathtype: ImplementationSpecific
  annotations: {}
  # kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: ""
      paths:
        - path: "/"
  #tls: []
  #  - secretName: sandbox-secret
  #    hosts:
  #      - chart-example.local      
deployment:
  apiVersion: "apps/v1"
  annotations:
    deployTime: "{{ .Values.deployTime }}"

operations_app:
  datasource:
    host: "operationsmysql"
keycloak:
  enabled: true 